### ISSUE TITLE
Carregar imagens do app de forma Assíncrona

### ISSUE THREAD

**Issue by marco-beduschi** [atendo-em-libras/atendo-em-libras#19]
## O problema
Nossas imagens da página **Sobre o Projeto** carregam sincronamente, ou seja, congelam o render enquanto estão baixando, então qualquer outro html que venha depois vai ter que esperar as imagens baixarem primeiro.

<img width="909" alt="Screen Shot 2020-08-27 at 10 53 38" src="https://user-images.githubusercontent.com/8469440/91451597-f5ae6c80-e853-11ea-8a3d-a222abbf4b58.png">

## A solução
Fazer o render de forma assíncrona, permitir que o render siga desenhando a página, e quando as imagens terminarem o download, o render volte e adicione elas na tela.

Esse artigo dá uma ideia de como fazer isso:
https://dev.to/prototyp/best-way-to-lazy-load-images-for-maximum-performance-27o1

**Comment by andre000** [comment]
Olá. Eu estava dando uma olhada no projeto e reparei que o `DropletAvatar` que carrega os avatares carrega as imagens pelo atributo `background-image`  do css, não via uma tag img. Isso impossibilita o uso da propriedade `loading="lazy"` que o artigo mencionava. Visto isso, eu pensei em duas soluções para contornar isso:

1.  Importar os participantes depois de renderizar a página. Com isso chegamos no mesmo propósito do lazy loading e também evitamos de precisar de algum outro plugin para navegadores que não suportam a propriedade  `loading="lazy"`. Ficaria algo assim:

`About.js`

```javascript
  ...
  const [participantes, setParticipantes] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchData = async () => {
      const { participantes: data } = await import('./participantes')
      setParticipantes(data)
      setLoading(false)
    }
    fetchData()
  }, [])

  ...

  <Box direction="row" wrap justify="center">
    {loading || participantes.map((participant) => (
      ...
    ))}
</Box>
```
2. Criar um componente similar ao `DropletAvatar` com uma tag img. Com isso conseguimos usar a propriedade  `loading="lazy"`, mas talvez seja necessário adicionar algum plugin para dar suporte a navegadores mais antigos.

Caso ache alguma dessas opções interessantes, ficaria feliz em contribuir com um PR

**Comment by marco-beduschi** [comment]
E aí Andre, beleza?

Desculpa a demora, não esperava receber uma resposta aqui tão cedo! 😆 
Muito daora as tuas soluções, ambas fazem sentido!

Sobre a primeira:
Não sabia que dava pra fazer um import async de módulos do app, nesse caso `./participantes`, que demais. Eu gosto dessa solução por enquanto porque parece a mais facil!

Sobre a segunda:
Era essa a abordagem que eu tava pensando mesmo, e dei uma olhada no "Can I Use..." e acho que por enquanto não precisamos nos preocupar com polyfills, ele já está disponível numa parcela grande de browsers.

As duas são opções viáveis, então você pode ficar a vontade pra escolher qual for mais facil/interessante pra ti!

Eu não sei se configurei o projeto corretamente pra pull requests externos, se tiver alguma problema, seja com o PR ou com entendimento do código, me pinga!

Valeu! 😄

**Comment by andre000** [comment]
Sem problemas :)
Eu vou ir com a primeira opção então. Vou começar aqui e qualquer coisa te aviso
